"""Añadir modelos Person, Image, Story, Tag y relaciones

Revision ID: 19ed32670f53
Revises: 765cbaab230e
Create Date: 2025-05-21 09:45:38.933594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19ed32670f53'
down_revision = '765cbaab230e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('story_tags',
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['historias.id_historias'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('story_id', 'tag_id')
    )
    op.drop_column('historias', 'etiqueta_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historias', sa.Column('etiqueta_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_table('story_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
