"""Crear tablas personas, imagenes e historias y relaciones

Revision ID: 765cbaab230e
Revises: 4f39316296bf
Create Date: 2025-05-21 09:36:27.157573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765cbaab230e'
down_revision = '4f39316296bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('procedencia', sa.String(length=30), nullable=True),
    sa.Column('profesion', sa.String(length=45), nullable=True),
    sa.Column('fecha_nacimiento', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id_persona')
    )
    op.create_table('historias',
    sa.Column('id_historias', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('administrador_id_admin', sa.Integer(), nullable=False),
    sa.Column('etiqueta_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['administrador_id_admin'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['id_persona'], ['personas.id_persona'], ),
    sa.PrimaryKeyConstraint('id_historias')
    )
    op.create_table('imagenes',
    sa.Column('id_imagen', sa.Integer(), nullable=False),
    sa.Column('url_imagen', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['personas.id_persona'], ),
    sa.PrimaryKeyConstraint('id_imagen')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagenes')
    op.drop_table('historias')
    op.drop_table('personas')
    # ### end Alembic commands ###
