"""Alinear modelos con BBDD final y añadir traducciones de historias

Revision ID: b118cfc8da05
Revises: ea10e3767f46
Create Date: 2025-05-22 12:07:35.852122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b118cfc8da05'
down_revision = 'ea10e3767f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrador',
    sa.Column('id_admin', sa.Integer(), nullable=False),
    sa.Column('nombre_admin', sa.String(length=45), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id_admin'),
    sa.UniqueConstraint('nombre_admin')
    )
    op.create_table('historias_traducciones',
    sa.Column('id_traduccion', sa.Integer(), nullable=False),
    sa.Column('historias_id_historias', sa.Integer(), nullable=False),
    sa.Column('codigo_idioma', sa.String(length=5), nullable=False),
    sa.Column('contenido_traducido', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['historias_id_historias'], ['historias.id_historias'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_traduccion'),
    sa.UniqueConstraint('historias_id_historias', 'codigo_idioma', name='uq_historia_idioma')
    )
    op.drop_index('username', table_name='admin_users')
    op.drop_table('admin_users')
    op.add_column('historias', sa.Column('Personas_id_persona', sa.Integer(), nullable=False))
    op.add_column('historias', sa.Column('Administrador_id_admin', sa.Integer(), nullable=False))
    op.add_column('historias', sa.Column('etiqueta_id_principal', sa.Integer(), nullable=True))
    op.drop_constraint('historias_ibfk_1', 'historias', type_='foreignkey')
    op.drop_constraint('historias_ibfk_2', 'historias', type_='foreignkey')
    op.create_foreign_key(None, 'historias', 'personas', ['Personas_id_persona'], ['id_persona'], ondelete='CASCADE')
    op.create_foreign_key(None, 'historias', 'etiquetas', ['etiqueta_id_principal'], ['etiqueta_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'historias', 'administrador', ['Administrador_id_admin'], ['id_admin'], ondelete='RESTRICT')
    op.drop_column('historias', 'id_persona')
    op.drop_column('historias', 'administrador_id_admin')
    op.drop_column('historias', 'contenido')
    op.drop_constraint('historias_has_etiquetas_ibfk_1', 'historias_has_etiquetas', type_='foreignkey')
    op.drop_constraint('historias_has_etiquetas_ibfk_2', 'historias_has_etiquetas', type_='foreignkey')
    op.create_foreign_key(None, 'historias_has_etiquetas', 'etiquetas', ['etiquetas_etiqueta_id'], ['etiqueta_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'historias_has_etiquetas', 'historias', ['historias_id_historias'], ['id_historias'], ondelete='CASCADE')
    op.add_column('imagenes', sa.Column('personas_id_persona', sa.Integer(), nullable=False))
    op.add_column('imagenes', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_constraint('imagenes_ibfk_1', 'imagenes', type_='foreignkey')
    op.create_foreign_key(None, 'imagenes', 'personas', ['personas_id_persona'], ['id_persona'])
    op.drop_column('imagenes', 'id_persona')
    op.add_column('personas', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('personas', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('personas', 'nombre',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('personas', 'procedencia',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personas', 'procedencia',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('personas', 'nombre',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('personas', 'updated_at')
    op.drop_column('personas', 'created_at')
    op.add_column('imagenes', sa.Column('id_persona', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'imagenes', type_='foreignkey')
    op.create_foreign_key('imagenes_ibfk_1', 'imagenes', 'personas', ['id_persona'], ['id_persona'])
    op.drop_column('imagenes', 'updated_at')
    op.drop_column('imagenes', 'personas_id_persona')
    op.drop_constraint(None, 'historias_has_etiquetas', type_='foreignkey')
    op.drop_constraint(None, 'historias_has_etiquetas', type_='foreignkey')
    op.create_foreign_key('historias_has_etiquetas_ibfk_2', 'historias_has_etiquetas', 'historias', ['historias_id_historias'], ['id_historias'])
    op.create_foreign_key('historias_has_etiquetas_ibfk_1', 'historias_has_etiquetas', 'etiquetas', ['etiquetas_etiqueta_id'], ['etiqueta_id'])
    op.add_column('historias', sa.Column('contenido', mysql.VARCHAR(length=500), nullable=False))
    op.add_column('historias', sa.Column('administrador_id_admin', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('historias', sa.Column('id_persona', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'historias', type_='foreignkey')
    op.drop_constraint(None, 'historias', type_='foreignkey')
    op.drop_constraint(None, 'historias', type_='foreignkey')
    op.create_foreign_key('historias_ibfk_2', 'historias', 'personas', ['id_persona'], ['id_persona'])
    op.create_foreign_key('historias_ibfk_1', 'historias', 'admin_users', ['administrador_id_admin'], ['id'])
    op.drop_column('historias', 'etiqueta_id_principal')
    op.drop_column('historias', 'Administrador_id_admin')
    op.drop_column('historias', 'Personas_id_persona')
    op.create_table('admin_users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'admin_users', ['username'], unique=True)
    op.drop_table('historias_traducciones')
    op.drop_table('administrador')
    # ### end Alembic commands ###
