"""Actualizar modelos Story y Tag según nuevo esquema de BD

Revision ID: ea10e3767f46
Revises: 19ed32670f53
Create Date: 2025-05-21 14:19:52.594034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea10e3767f46'
down_revision = '19ed32670f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etiquetas',
    sa.Column('etiqueta_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('etiqueta_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('historias_has_etiquetas',
    sa.Column('historias_id_historias', sa.Integer(), nullable=False),
    sa.Column('etiquetas_etiqueta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etiquetas_etiqueta_id'], ['etiquetas.etiqueta_id'], ),
    sa.ForeignKeyConstraint(['historias_id_historias'], ['historias.id_historias'], ),
    sa.PrimaryKeyConstraint('historias_id_historias', 'etiquetas_etiqueta_id')
    )
    op.drop_table('story_tags')
    op.drop_index('name', table_name='tags')
    op.drop_table('tags')
    op.alter_column('historias', 'contenido',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('historias', 'contenido',
               existing_type=sa.String(length=500),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.create_table('tags',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'tags', ['name'], unique=True)
    op.create_table('story_tags',
    sa.Column('story_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['historias.id_historias'], name='story_tags_ibfk_1'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='story_tags_ibfk_2'),
    sa.PrimaryKeyConstraint('story_id', 'tag_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('historias_has_etiquetas')
    op.drop_table('etiquetas')
    # ### end Alembic commands ###
